name: Rendder
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_DEPLOY_URL }}
