name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ fromJson(github.event.commits.*.message) }}
          SKIP_CONDITION: ${{ !contains(join(github.env.COMMIT_MESSAGES, ' '), '#skip') }}
        run: echo "$COMMIT_MESSAGES"
        
      - name: skipped
        run: echo ${{ github.env.SKIP_CONDITION }}
